# Generated by Django 2.2 on 2019-04-07 14:55

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Product Name')),
                ('product_uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for product across services', unique=True, verbose_name='Unique ID for product')),
                ('product_category', models.CharField(max_length=25)),
                ('discontinued', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'product_category')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID for Event')),
                ('object_id', models.CharField(max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('body', django_extensions.db.fields.json.JSONField(default=dict)),
                ('sent', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_events', to='contenttypes.ContentType')),
            ],
        ),
    ]
